config/urls.py
from django.conf import settings # 画像を表示する設定
from django.conf.urls.static import static # 画像を表示する設定
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pictures.urls')),
]

"""画像を表示する設定 settingsがDEBUGの場合、MEDIA_URLとMEDIA_ROOTをurlpatternsに保存する"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pictures/urls.py
from django.urls import path

from .views import (PictureCreateView, PictureDeleteView, PictureDetailView,
                    PictureList, PictureUploadView, PictureUpdateView,
                    CheckValidationView,CheckValidationViewByModelForm,
                    EditViewByForm,EditView,PictureDeleteByForm,CommentView,
                    Login,Logout,SignUp)


app_name = 'pictures'

urlpatterns = [
    path('', PictureCreateView.as_view(), name='top'),
    path('upload/', PictureUploadView.as_view(), name='picture_upload'),
    path('list/', PictureList.as_view(), name='picture_list'),
    path('delete/<int:pk>/', PictureDeleteView.as_view(), name='picture_delete'),
    path('delete_form/<int:pk>/', PictureDeleteByForm.as_view(), name='picture_delete_form'),
    path('detail/<int:pk>/', PictureDetailView.as_view(), name='picture_detail'),
    path('edit/<int:pk>/', PictureUpdateView.as_view(), name='picture_edit'),
    path('edit_form/<int:pk>/', EditViewByForm.as_view(), name='picture_edit_form'),
    path('edit_updateview/<int:pk>/', EditView.as_view(), name='picture_edit_update'),
    path('check_clean/', CheckValidationView.as_view(), name='picture_clean'),
    path('check_clean_model/', CheckValidationViewByModelForm.as_view(), name='picture_clean_model'),
    path('comment/<int:pk>/', CommentView.as_view(), name='comment'),
    path('login/',Login.as_view(),name='login'),
    path('logout/', Logout.as_view(), name='logout'),
    path('signup/', SignUp.as_view(), name='signup'),
]

pictures/models.py
from django.conf import settings
from django.db import models

class UploadFile(models.Model):
    """ファイルとファイルネームのモデル"""

    file = models.ImageField(upload_to='media/images/')
    file_name = models.CharField(max_length=100, verbose_name='ダウンロード時に使うファイル名')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.file_name

class Comment(models.Model):
    """コメントモデル"""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField(verbose_name='コメント')
    target = models.ForeignKey(UploadFile, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

pictures/forms.py
from django import forms
from django.core import validators

from .models import UploadFile, Comment
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from accounts.models import CustomUser


class UploadForm(forms.ModelForm):
    """画像をアップロードするフォーム"""
    file_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'file-name'}))

    class Meta:
        model = UploadFile
        fields = ['file', 'file_name']
        # fields = '__all__'
        # exclude = ['user']
        # fields = ('file', 'file_name')

class EditForm(forms.ModelForm):
    """画像を編集(差替）するフォーム"""

    class Meta:
        model = UploadFile
        fields = ['file', 'file_name']
        # fields = '__all__'

    def is_valid(self):
        print('modelform_isvarid実行')
        return super().is_valid()


class CheckValidationForm(forms.Form):
    """clean処理を用いたフォーム作業 CheckValidationView(FormView)で使用"""

    file = forms.ImageField(label='登録ファイル')
    file_name = forms.CharField(label='ファイル名')

    def clean_file(self):
        """
        ファイル容量が500KBを超えていたらエラーを返す

        :param: file:バリデーションを実行された後に生成される辞書
        　　　　指定されたキーが存在しない場合はNoneを返すself.cleanded_data.get()メソッドにしてみた
        :return:エラーの場合はValidationErrorを返す:
                エラーがない場合はfileオブジェトクを返す
        """

        file = self.cleaned_data.get('file')

        print(self.cleaned_data['file'])  # ULCA0005.JPG
        print(type(self.cleaned_data['file']))  # <class 'django.core.files.uploadedfile.TemporaryUploadedFile'>

        if file and file.size > 500 * 1000:
            raise forms.ValidationError('ファイルサイズは500KB以下にしてください')
        return file

    def clean_file_name(self):
        """
        特定のフィールド属性をクリーニングする
        file_nameが"test"だったら、エラーを返す

        :param: file:バリデーションを実行された後に生成される辞書
        　　　　指定されたキーが存在しない場合はNoneを返すself.cleanded_data.get()メソッドにしてみた
        :return:エラーの場合はValidationErrorを返す:
                エラーがない場合はfileオブジェトクを返す
        """

        file_name = self.cleaned_data['file_name']
        # cleaned_data = super().clean()
        # file_name = cleaned_data['file_name']
        print(file_name, "check_clean_file", sep="☆")
        if file_name == "test":
            raise forms.ValidationError('ファイル名にtestという名前は使用できません')
        return file_name


class CheckValidationModelForm(forms.ModelForm):
    """clean処理を用いたフォーム作業 ModelForm"""
    class Meta:
        model = UploadFile
        fields = ['file', 'file_name']

    def clean_file_name(self):
        file_name = self.cleaned_data['file_name']
        print("formのcleanソメッドでfile_name検索：", file_name)
        if 'test' in file_name:
            raise forms.ValidationError(f'{file_name}はだめてす')
        return file_name


class EditByFormsForm(forms.Form):
    """画像を編集(差替）するフォーム"""

    file = forms.ImageField(label='編集ファイル')
    file_name = forms.CharField(label='編集ファイル名')

    def is_valid(self):
        print("is_valid()が実行されました")
        return super().is_valid()

    def get_initial(self):
        instance = UploadFile.objects.get(pk=self.kwargs['pk'])
        return {"file": instance.file, "file_name": instance.file_name}

    def clean_file(self):
        file = self.cleaned_data.get('file')
        if file and file.size > 500 * 1000:
            raise forms.ValidationError('ファイルサイズは500KB以下にしてください')
        return file


class DeleteForm(forms.Form):
    """画像を削除するフォーム"""

    id = forms.IntegerField(label='削除する画像のID', widget=forms.HiddenInput)

class CommentForm(forms.ModelForm):
    """コメントを投稿するフォーム"""

    class Meta:
        model = Comment
        fields = ('comment',)




# class LoginForm(AuthenticationForm):
#     """
#     LoginFormの__init__メソッドは、親クラスの__init__メソッドを呼び出し、
#     LoginFormのインスタンスを初期化します。
#     そして、LoginFormの各フィールド（例えば、ユーザー名やパスワード）に対して、
#     CSSのクラス名を追加することで、フォームのスタイリングを変更しています。
#
#     具体的には、self.fields.values()でLoginFormの全てのフィールドにアクセスし、
#     それぞれのフィールドのwidgetのattrs属性に"form-control"というクラス名を追加しています。
#     "form-control"クラスは、Bootstrapなどのフロントエンドライブラリで使用されるクラスで、
#     テキストフィールドやボタンなどの要素をスタイリングするために使われます。
#     このコードを使うことで、ログインフォームがより見やすく、使いやすくなります。
#     """
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         for field in self.fields.values():
#             field.widget.attrs['class'] = 'form-control'

pictures/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView, FormView, View
from django.views.generic.edit import ModelFormMixin
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect

from .forms import UploadForm, EditForm, CheckValidationForm, CheckValidationModelForm, EditByFormsForm, DeleteForm, \
    CommentForm
from accounts.forms import SignupForm, LoginForm
from .models import UploadFile, Comment
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin


class CheckMyPostMixin(UserPassesTestMixin):
    """Mixinクラス　ログインユーザーの投稿かどうかを判定する"""

    raise_exception = True
    def test_func(self):
        """ログインユーザーの投稿かどうかを判定する"""

        post = UploadFile.objects.get(id=self.kwargs['pk'])
        return post.user == self.request.user

class MyFormValidMixin:
    """Mixinクラス　新規登録、編集時のファイルの処理を共通化したメソッドを定義"""

    def my_form_valid(self, form):
        """投稿されたファイル名を入力したファイル名＋日付にする"""

        instance = form.save(commit=False)
        if instance.file:
            instance.file_name = f'{instance.file_name}_{datetime.today().strftime("%Y%m%d")}'
        instance.save()
        return super().form_valid(form)


class PictureCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    """[1]forms.py　class UploadForm(forms.ModelForm)を引数にとる"""

    model = UploadFile
    form_class = UploadForm
    template_name = 'top.html'

    def get_context_data(self, **kwargs):
        """
        fromに表示するタイトル、uploadするフオームクラスを戻り値として返す
        :param context["title"] :フォームに表示するタイトル名
               context["upload_form"] :class UploadForm
        :return:context タイトルとモデルフォームを格納した辞書型オブジェクト
        """

        context = super().get_context_data(**kwargs)

        context.update({
            'title': "☆画像のアップロード☆",
            'upload_form': UploadForm(),
        })
        return context

    def form_valid(self, form):
        """
        投稿されたファイルのファイル名を取得して file_name 属性に格納する
        :param form:　upload.htmlのテンプレートフォーム
            　　 instance:データベースへ保存する前のモデルインスタンス
        :return:指定されたURLにリダイレクト
        """
        """フォームのバリデーション"""
        instance = form.save(commit=False)
        instance.user_id = self.request.user.id
        instance.save()
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        """
        更新時のメッセージを表示
        :param cleaned_data:'file(InMemoryUploadedFile)'と'file_name'の辞書
        {'file': <InMemoryUploadedFile: IMG_2174.JPG (image/jpeg)>, 'file_name': 'rapping'}
        :return:カスタマイズした成功時のメッセージ(新規登録）
        """

        return f'id:{self.object.id} ファイルを{cleaned_data.get("file_name")}で新規登録しました☆'


    def get_success_url(self):
        """成功時にリダイレクトするURL"""

        return self.request.path


class PictureUploadView(LoginRequiredMixin, CreateView):
    """[2] upload_file.html formのテンプレートを活用する"""

    model = UploadFile
    form_class = UploadForm
    template_name = 'upload_file.html'

    def form_valid(self, form):
        """
        投稿されたファイルのファイル名を取得して file_name 属性に格納する
        :param form:　upload.htmlのテンプレートフォーム
            　　 instance:データベースへ保存する前のモデルインスタンス
        :return:指定されたURLにリダイレクト
        """
        """フォームのバリデーション"""
        instance = form.save(commit=False)
        instance.user_id = self.request.user.id
        instance.save()
        messages.success(self.request, 'ファイルをアップロードしました。')
        return super().form_valid(form)

    def get_success_url(self):
        return self.request.path


class PictureList(ListView):
    """画像のid、写真，削除リンクを表示する一覧ページ"""

    model = UploadFile
    template_name = 'list_file.html'


class PictureDeleteView(CheckMyPostMixin, DeleteView):
    """画像を削除するページ"""

    model = UploadFile
    template_name = 'delete_file.html'
    success_url = reverse_lazy('pictures:picture_list')


class PictureDeleteByForm(CheckMyPostMixin, FormView):
    """フォームから画像を削除するページ"""

    model = UploadFile
    template_name = 'delete_file_2.html'
    form_class = DeleteForm
    success_url = reverse_lazy('pictures:picture_list')

    def form_valid(self, form):
        """フォームの入力値を取得して、画像を削除する"""

        id = form.cleaned_data['id']
        UploadFile.objects.get(id=id).delete()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = '画像を削除する'
        return context


class PictureDetailView(DetailView):
    """詳細情報を表示するページ"""

    model = UploadFile
    template_name = 'detail_file.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # ログインしているユーザーの名前を取得して、コンテキストに渡す
        return context


class PictureUpdateView(CheckMyPostMixin, SuccessMessageMixin, UpdateView):
    """選択した画像を差し替える編集ページ
    　　modelform使用たと更新できる。forms.Formは更新できない"""

    model = UploadFile
    template_name = 'edit_file.html'
    form_class = EditForm
    success_message = '更新成功'

    def get_success_url(self):
        """成功した時は、updateページにリダイレクト
        kwargsは、単体モデルインスタンスのid
        """

        return reverse_lazy('pictures:picture_edit', kwargs={'pk': self.object.id})

    def get_success_message(self, cleaned_data):
        """
        更新時のメッセージを表示
        :param cleaned_data:'file(InMemoryUploadedFile)'とformに入力した文字列'file_name'の辞書
        {'file': <InMemoryUploadedFile: IMG_2174.JPG (image/jpeg)>, 'file_name': 'rapping'}
        :return:成功時のメッセージ
        """

        return f'id：{self.object.id},file_name: {self.object.file_name}に変更しました。フォームに入力した文字列は{cleaned_data["file_name"]}です'

    def get_context_data(self, **kwargs):
        """
        fromに表示するタイトル、uploadするフオームクラスを戻り値として返す
        :param:context["id"] :フォームに表示するオブジェクトのid
               context["title"] :フォームに表示するタイトル名
               context["date"] :フォームに表示する現在日時
               context["upload_form"] :class UploadForm
        :return:context タイトルとモデルフォームを格納した辞書型オブジェクト
        """

        context = super().get_context_data(**kwargs)
        edit_form = EditForm()
        context['id'] = self.object.id
        context['title'] = 'の変更ページです'
        context['date'] = f'ただいまの時刻は、{datetime.today().strftime("%Y/%m/%d %H:%M")}です'
        context['edit_form'] = edit_form
        return context

    def form_valid(self, form):
        """
        投稿されたファイルのファイル名を取得して file_name 属性に格納する
        :param form:　upload.htmlのテンプレートフォーム
            　　 instance:データベースへ保存する前のモデルインスタンス
        :return:指定されたURLにリダイレクト
        """
        """フォームのバリデーション"""
        instance = form.save(commit=False)
        instance.user_id = self.request.user.id
        instance.save()
        return super().form_valid(form)

    # def form_valid(self, form):
    #     """form_validメソッドだけを定義したMixinクラス(MyFormValidMixin)を呼び出す"""
    #
    #     return self.my_form_valid(form)


class CheckValidationView(LoginRequiredMixin, FormView):
    """form.Formsクラスを継承したクラス"""

    template_name = 'check_validation.html'
    form_class = CheckValidationForm
    success_url = reverse_lazy('pictures:picture_clean')

    def form_valid(self, form):
        """
        フォームの送信が成功した時の処理

        :param: file:フォームで登録した画像
                file_name:フォームで入力したファイル名
        :return:

        """

        file = form.cleaned_data.get("file")
        file_name = form.cleaned_data.get("file_name")
        user = self.request.user
        data = {'file': file, 'file_name': file_name, 'user': user}
        instance = UploadFile(**data)
        instance.save()
        return super().form_valid(form)


class CheckValidationViewByModelForm(LoginRequiredMixin, CreateView):
    """
    モデルフォームを使ってフォームのバリデーションを確認する


    """
    model = UploadFile
    template_name = 'check_validation_model.html'
    form_class = CheckValidationModelForm
    success_url = reverse_lazy('pictures:picture_clean_model')

    def form_valid(self, form):
        """フォームのバリデーション"""
        instance = form.save(commit=False)
        instance.user_id = self.request.user.id
        instance.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        """フォームのバリデーション"""
        print("Viewのform_invlidメソッドの出力", form.errors, sep="：")
        return super().form_invalid(form)


class EditView(CheckMyPostMixin, View):
    """ファイルを編集"""

    def get(self, request, *args, **kwargs):
        edit_form = EditByFormsForm()
        return render(request, 'edit_file_3.html', context={'edit_form': edit_form})

    def post(self, request, *args, **kwargs):
        edit_form = EditByFormsForm(request.POST, request.FILES)
        if edit_form.is_valid():
            data = edit_form.cleaned_data
            print(data['file'], data['file_name'])
            instance = UploadFile.objects.get(id=self.kwargs['pk'])
            print(instance, '変更前のinsetanceです')
            instance.file = data['file']
            instance.file_name = data['file_name']
            instance.save()
            print(instance, '変更後のinsetanceです')
        return render(request, 'edit_file_3.html', context={'edit_form': edit_form})
        # reverse razyは'__proxy__' object has no attribute 'get'


class EditViewByForm(CheckMyPostMixin, FormView):
    """ファイルを編集するFromViewクラス"""

    model = UploadFile
    template_name = 'edit_file_2.html'
    form_class = EditByFormsForm
    success_url = reverse_lazy('pictures:picture_list')

    def get_initial(self):
        """初期値を設定する"""
        instance = UploadFile.objects.get(id=self.kwargs['pk'])
        print(instance.file.url, "fileのulr")
        return {'file': instance.file, 'file_name': instance.file_name, 'file_url': instance.file.url}

    def form_valid(self, form):
        """フォームのバリデーション"""
        data = form.cleaned_data

pictures/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}画像登録アプリ{% endblock %}</title>
  <!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD">

    <style type="text/css">
    body{
        width: 80%;
        margin: 0 auto;
    }
    h1{
        font-weight: 400;
        text-align: center;
        color: #0000ff;
        background-color: #00ffff;
    }
    p{
        font-size: 20px;
        color: deeppink;
    }
    a{
        font-size: 20px;
        color: darkblue;
        line-height: 2em;
    }

</style>

</head>
<body>
    <h1>プジさんの画像登録アプリ</h1>
    <!　block endblockの部分は継承先が記載する -->
    {% block content %}{% endblock %}
</body>
</html>

pictures/templates/check_validation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.file.label }}：{{ form.file }}
            <br>
            {{ form.file_name.label }}:{{ form.file_name }}

            {% if form.file_name.errors %}
                <div style="color: red">  {{ form.file_name.errors.as_text }}</div>
            {% endif %}

{#            <p>{{ form.as_p }}</p>#}
            <p><input type="submit" value="アップロード"></p>
        </form>
        <br>
        <P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></p>
        </br>

</body>
</html>

pictures/templates/check_validation_model.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.file.label }}：{{ form.file }}
            <br>
            {{ form.file_name.label }}:{{ form.file_name }}

            {% if form.file_name.errors %}
                <div style="color: red">  {{ form.file_name.errors.as_text }}</div>
            {% endif %}

{#            <p>{{ form.as_p }}</p>#}
            <p><input type="submit" value="アップロード"></p>
        </form>
        <br>
        <P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></p>
        </br>

</body>
</html>

pictures/templates/comment_form.html
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="更新">
</form>

pictures/templates/delete_file.html
<form method="POST">
    {% csrf_token %}
    <p>{{ object }}を削除します</p>
    <p>{{ object.name }}</p>
    <input type="submit" value="削除">
</form>

pictures/templates/delete_file_2.html
<form method="POST">
    {% csrf_token %}
    <p>{{ object }}を削除します</p>
    <p>{{ object.name }}</p>
    <input type="submit" value="削除">
</form>

pictures/templates/edit_file.html
<h1>id:{{ id }} {{ title }}</h1>

<h2>{{ date }}</h2>

<h3>
{% if messages %}
    {% for message in messages %}
        {{ message.message }}
    {% endfor %}
{% endif %}
</h3>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.as_p }}
    <input type="submit" value="更新">
</form>
<br>
<p><img width="200px" height="200px" src="{{ object.file.url }}"></img></p>

<P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></P>

pictures/templates/edit_file_3.html
<h1>formの編集画面</h1>

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ edit_form.file.label }}☆{{ edit_form.file }}
    <br>
    {% if edit_form.file.errors %}
        <div style="color:red">{{ edit_form.file.errors.as_text }}</div>
    {% endif %}
    <br>
    {{ edit_form.file_name.label }}☆{{ edit_form.file_name }}
    <br>
    <input type="submit" value="更新(form)">
</form>
<br>
{#<p><img width="200px" height="200px" src="{{ file.path }}"></p>#}
<P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></P>

pictures/templates/index.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
</head>
<body>
    <h1>{{title}}</h1>
    <div>
        {% if messages %}
        {% for message in messages %}
            {{ message.message }}
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ upload_form.as_p }}</p>
            <p><input type="submit" value="アップロード"></p>
        </form>
        <br>
        <P><a href="{% url 'pictures:list' %}">一覧ページへ</a></p>
        </br>
    </div>
</body>
</html>

pictures/templates/list_file.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'pictures/css/style.css' %}">
    <script src="https://kit.fontawesome.com/41f9c2a86b.js" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <p>{% if user.is_authenticated %}
              ログイン名：{{ request.user }}<br>
              <a href="{% url 'pictures:logout' %}">ログアウト</a>
           {% else %}
                <a href="{% url 'pictures:login' %}">ログイン:</a><br>
                <a href="{% url 'pictures:signup' %}">Signup:</a><br>
           {% endif %} </p>
        <P><a href="{% url 'pictures:top' %}">model formクラスの登録ページへ</a>  file_name：file_name+yyyymmdd</p>
        <P><a href="{% url 'pictures:picture_upload' %}">upload.htmlのフォームの登録ページへ</a>  file_name：画像ファイル名（拡張子は取る）</p>
        <P><a href="{% url 'pictures:picture_clean' %}">forms.Formsの登録ページ　cleanメソッドチェック</a>  </p>
        <P><a href="{% url 'pictures:picture_clean_model' %}">forms.ModelFormsの登録ページ　cleanメソッドチェック</a> </p>
        <br>
        <table>
        <tr>
            <th class="th_id">ID</th>
            <th class="th_image">画像</th>
            <th class="th_file_name">ファイル名</th>
            <th class="th_delete">削除</th>
            <th class="th_edit_1">編集(update)</th>
            <th class="th_edit_2">編集(form)</th>
            <th class="th_detail">詳細</th>
            <th class="th_user">作成者</th>
        </tr>

        {% for object in uploadfile_list %}
        <tr>
                <td class="td_id"><p>{{ object.id }}</td>
                <td class="td_image"><img width="100px" heigth="100px" src="{{ object.file.url }}"></td>
                <td class="td_file_name">{{ object.file_name }}</td>
                <td class="td_delete"><a href="{% url 'pictures:picture_delete' pk=object.id %}">削除</a></td>
                <td class="td_edit_1"><a href="{% url 'pictures:picture_edit' pk=object.id %}">編集</a></td>
                <td class="td_edit_2"><a href="{% url 'pictures:picture_edit_form' pk=object.id %}">編集</a></td>
                <td class="td_detail"><a href="{% url 'pictures:picture_detail' pk=object.id %}">詳細</a></td>
                <td class="td_user"><p>{{ object.user.username }}</td>
        </tr>
        {% endfor %}
    </div>
</body>
</html>
{% endblock %}

pictures/templates/login.html
{% extends 'base.html' %}

{% block content %}
  <h2>Login AuthenticationFormを使用してログインフォームをレンダリングする</h2>
  <form method="post">
    {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
          {{ field.label }}
          {{ field }}
          <br>
          {{ field.errors }}
      {% endfor %}
{#      {{ form.as_p }}#}
    <button type="submit">Login</button>
  </form>
{% endblock %}

pictures/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Signup</h2>
  <form method="post">
    {% csrf_token %}
      {{ form.non_field_errors }}
      {% for field in form %}
          {{ field.label }}
          {{ field }}
          <br>
          {{ field.errors }}
      {% endfor %}
{#      {{ form.as_p }}#}
    <button type="submit">Login</button>
  </form>
{% endblock %}

pictures/templates/top.html
<!doctype html>
<html lang="ja">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>
<body>
    <h1>{{title}}</h1>
    <div>
        {% if messages %}
        {% for message in messages %}
            {{ message.message }}
        {% endfor %}
        {% endif %}
    </div>
    <div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ upload_form.as_p }}</p>
            <p><input type="submit" value="アップロード"></p>
        </form>
        <br>
        <P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></p>
        </br>
    </div>
</body>
</html>

pictures/templates/upload_file.html
<div id="messages">
    {% if messages %}
        {% for message in messages %}
            <p>{{ message }}</p>
        {% endfor %}
    {% endif %}
</div>
<div id="form-area">
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit">送信</button>
    </form>
    <br>

    <P><a href="{% url 'pictures:picture_list' %}">一覧ページへ</a></P>

</div>